# Loading Training/Validation/Test Datasets for Task-B

This second notebook (Part-2) provides a step-by-step guide on loading/preparing the training/validation/test data for the TalentCLEF shared-task B.
In this notebook you will see how to load the training/validation/test dataset of the task and a simple listing of those datasets.

- Preparing task-B dataset
- Setting up dataset path (training, validation, and test)
- Loading training data files and reporting the statistics
- Loading validation data files and reporting the statistics
- Loading test data files and reporting the statistics

## Import Required Libraries

In [1]:
import os
import sys
import pandas as pd
import json

## Preparing data (Task B)

### Setting up data path

In [ ]:
root_data_path="taskB"

In [ ]:
#Training data path
taskB_training_path = os.path.join(root_data_path, "training")

#validation data path
validation_data_path=os.path.join(root_data_path, "validation")

#testing data path
test_data_path=os.path.join(root_data_path, "test")

### Training data loading

#### Training data dictionary

The training data for Task B is shared in 3 files:
- `job2skill.tsv`: This file has been curated to include the most representative skills for each job title in <a href="https://esco.ec.europa.eu/en">ESCO</a>. This file contains three columns:
  - `job_id`: ESCO identifier for the job position.
  - `skill_id`: ESCO identifier for the skill.
  - `rel_type`: Indicator specifying whether the skill_id is essential or optional for a specific job_id. It can have the value “essential” or “optional.”

- `jobid2terms.json`: This JSON file contains job_id identifiers used in the training set for Task B as keys, and a list of valid lexical variants for each identifier as values.

- `skillid2terms.json`: This JSON file contains skill_id identifiers as keys, and a list of valid lexical variants for each identifier as values.

#### Reading Job2Skill data file

In [ ]:
# Read job2skill file
job2skill = pd.read_csv(os.path.join(taskB_training_path, 'job2skill.tsv'),
                        sep="\t",
                        names=["job_id","skill_id","rel_type"])

print ("No. of job_id and skill_id triple: {}".format(job2skill.shape[0]))
job2skill.head()

##### Listing the first 10 skill ids

In [ ]:
job2skill['skill_id'][:10]

#### Reading Job2Terms file

In [ ]:
# Read json files
jobid2terms_path = os.path.join(taskB_training_path, "jobid2terms.json")
print (jobid2terms_path)

In [ ]:
with open(os.path.join(jobid2terms_path), 'r') as file:
    jobid2terms = json.load(file)

In [ ]:
print ("Total job ids: {}".format(len(jobid2terms)))

#### Reading Skilled2Terms

In [ ]:
# Read json files
skillid2terms_path = os.path.join(taskB_training_path, "skillid2terms.json")
print (skillid2terms_path)

In [ ]:
with open(os.path.join(skillid2terms_path), 'r') as file:
    skillid2terms = json.load(file)

In [ ]:
print ("Total skill ids: {}".format(len(skillid2terms)))

#### Play with Job-id, Skill-id, Job-id-terms, and Skill-id-terms.

##### Expanding Job2Skill with Terms Mapping

In [ ]:
job2skill["job_terms"] = job2skill["job_id"].map(jobid2terms)
job2skill["skill_terms"] = job2skill["skill_id"].map(skillid2terms)

In [ ]:
job2skill.describe()

**Let's see the skills for a specific job_id.**

In [ ]:
job_id_to_search = job2skill.job_id.to_list()[100]
job_data = job2skill[job2skill.job_id == job_id_to_search]

**The job titles of the selected job_id are:**

In [ ]:
job_data.job_terms.iloc[0]

**For that job_id we fin 9 essential skills and 1 optional skill:**

In [ ]:
job_data.rel_type.value_counts()

The list of skills related to the job_id are:

In [ ]:
job_data.skill_terms.to_list()[0]

In [ ]:
job2skill.job_id.to_list()[100]

### Validation data loading

#### Validation data path setup

In [ ]:
validation_queries_path = os.path.join(validation_data_path, "queries")
validation_corpus_elements_path = os.path.join(validation_data_path, "corpus_elements")

#### Load queries and corpus elements

In [ ]:
validation_queries = pd.read_csv(validation_queries_path, sep="\t")
validation_corpus_elements = pd.read_csv(validation_corpus_elements_path, sep="\t")

In [ ]:
print ("Number of queries and copurs elements in validation dataset: {} and {}".format(len(validation_queries), len(validation_corpus_elements)))

In [ ]:
print ("validation query samples:")
validation_queries.head()

In [ ]:
validation_queries.jobtitle[0]

In [ ]:
print ("validation corpus elements samples:")
validation_corpus_elements.head()

In [ ]:
validation_corpus_elements.skill_aliases[0]

### Test data loading

#### Test data path setup

In [54]:
test_queries_path = os.path.join(test_data_path, "queries")
test_corpus_elements_path = os.path.join(test_data_path, "corpus_elements")

#### Load queries and corpus elements

In [55]:
test_queries = pd.read_csv(test_queries_path,sep="\t")
test_corpus_elements = pd.read_csv(test_corpus_elements_path, sep="\t")

In [56]:
print ("Number of queries and copurs elements in test dataset: {} and {}".format(len(test_queries), len(test_corpus_elements)))

Number of queries and copurs elements in test dataset: 1520 and 1986

In [57]:
print ("test query samples:")
test_queries.head()

test query samples:

       q_id                            jobtitle
0  15ec5e80                  Qdoba Mexican Eats
1  a0d97669                         Hairstylist
2  4b3976f7                       Digital Logic
3  a3bc11cc  Interstate/Local Moving Contractor
4  e12ee1fd                      Press Operator

In [59]:
test_queries.jobtitle[0]

'Qdoba Mexican Eats'

In [58]:
print ("test corpus elements samples:")
test_corpus_elements.head()

test corpus elements samples:

,c_id,esco_uri,skill_aliases
0,f3a278e7,http://data.europa.eu/esco/skill/77e41477-4ecf...,['recruiting and hiring']
1,2938fcd6,http://data.europa.eu/esco/skill/450de541-797a...,"['sales activities', 'sales exercises', 'a sal..."
2,7b3c55d4,http://data.europa.eu/esco/skill/0fbaceff-df05...,"['carry out job analysis', 'carrying out job a..."
3,572ec5d6,http://data.europa.eu/esco/skill/714eebcb-569a...,"['develop staff', 'help strengthen staff', 'bu..."
4,73f0560b,http://data.europa.eu/esco/skill/5aa57bdc-5765...,"['hire human resources', 'hire experienced peo..."

In [60]:
test_corpus_elements.skill_aliases[0]

"['recruiting and hiring']"